### ISSUE TITLE
[DataCap Application] AINN Layer2 

### ISSUE THREAD

**Issue by yuxlantian** [NDLABS-Leo/Allocator-Pathway-ND-CLOUD#15]
### Version

1

### DataCap Applicant

AINN Layer2

### Project ID

003

### Data Owner Name

AINN 

### Data Owner Country/Region

United States

### Data Owner Industry

Web3 / Crypto

### Website

https://anvm.io/

### Social Media Handle

https://twitter.com/AINNLayer2

### Social Media Type

Twitter

### What is your role related to the dataset

Dataset Owner

### Total amount of DataCap being requested

10PiB

### Expected size of single dataset (one copy)

1PiB

### Number of replicas to store

10

### Weekly allocation of DataCap requested

1PiB

### On-chain address for first allocation

f1ccqyhokaxxgdsdh7oayfxxzminsf6gyu6duodaa

### Data Type of Application

Private Commercial/Enterprise

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
AINN Layer2 Description： 
 
- Narrative Innovation: The first Bitcoin Layer 2 aimed at supporting the mass adoption of AI applications, with the goal of advancing the deep integration of Web3 and AI, benchmarking Merlin & Bittensor. 
 
- Community Support: An ecosystem project strongly supported by the AINN community, currently one of the first key supported inscription by the Binance web3 wallet, with a market value exceeding $50 million. AINN Layer2 will use AINN as gas consumption and the issued assets as governance tokens, with AINN's strong community and ecological support. 
 
- Technology Leadership: Bitcoin EVM-compatible Layer2 with multiple AI subnets to lay a foundation for bridging AI models, data, and algorithms. 
 
- Strong Background: The team consists of graduates from top American universities, chief scientists from startup financed by top venture capital such as Sequoia, and also get support from some of the largest Bitcoin holders. The initial phase targets a TVL of $1 billion. 
 

- Project Stage: Currently in the social point fission stage, with over 70,000 social accounts and Bitcoin wallet addresses bound. The testnet will be launched at the beginning of March for staking, and the mainnet will be launched in mid-March.
```

### Is this project associated with other projects/ecosystem stakeholders?

Yes

### If answered yes, what are the other projects/ecosystem stakeholders

```text
- Ecosystem Building: Currently, there are multiple eco projects such as AINN Swap, AINN Growth,  AINN Image, Public AI, and innovative inscription issuance protocols under construction.
```

### Describe the data being stored onto Filecoin

```text
Transaction data on the chain, as well as our AI model, and related AI Dapp application data
```

### Where was the data currently stored in this dataset sourced from

My Own Storage Infra

### If you are a data preparer. What is your location (Country/Region)

None

### If you are a data preparer, how will the data be prepared? Please include tooling used and technical details?

```text
Our lead SP will process the original data and generate the car file, then backup in 10* copies.
```

### If you are not preparing the data, who will prepare the data?  (Provide name and business)

```text
Our storage providers
```

### Has this dataset been stored on the Filecoin network before? If so, please explain and make the case why you would like to store this dataset again to the network. Provide details on preparation and/or SP distribution.

```text
no
```

### Please share a sample of the data

```text
https://stake.anvm.io/bridge
https://airdrop.anvm.io/
https://airdrop.anvm.io/leaderboard
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [ ] I confirm

### If you chose not to confirm, what was the reason

```text
those are encrypted data
```

### What is the expected retrieval frequency for this data

Monthly

### For how long do you plan to keep this dataset stored on Filecoin

More than 3 years

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China, Africa, North America, South America, Europe, Australia (continent), Antarctica

### How will you be distributing your data to storage providers

Cloud storage (i.e. S3), HTTP or FTP server, IPFS, Shipping hard drives, Lotus built-in data transfer, Venus built-in data transfer

### How did you find your storage providers

Slack, Filmine, Big Data Exchange, Partners

### Please list the provider IDs and location of the storage providers you will be working with.

```text
f03046248 / Pinapple / HK
f02956383 / Future / HK
f02948413 / FineTune / sichuan
f02226869 / LuckyMine / LA
f02837293 / FiveByte / Seoul
```

### How do you plan to make deals to your storage providers

Boost client

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by NDLABS-Leo** [comment]
@yuxlantian 

Thank you for your application, according to the rules of fil+, I need to review your application for a number of things, once approved will gradually provide Datacap for you to carry out data storage projects:

1、Please explain your relationship to the project you are applying for and how you can demonstrate that you can be held accountable for the project.
2、Please understand the significance of the project when applying for this channel, and explain the reason for your application.
3、Please make sure that you are aware of the principles of multi-region, multi-backup, retrievability and data authenticity for the project to proceed.
4、Whether the disclosed nodes will be followed up according to this list
5、I will ask you to store a small amount of data at the beginning of the project, so that we can retrieve the data on a sample basis.

**Comment by NDLABS-Leo** [comment]
@yuxlantian Ok, the information has been received, but it only supports that you can get a small amount of DC from our side for testing, more amount will be available only after you store the data and pass our sampling. We hope you will be able to store your project in a compliant manner.

**Comment by NDLABS-Leo** [comment]
Upon review, the data is consistent with the pre-disclosed types and will be further

**Comment by NDLABS-Leo** [comment]
checker:manualTrigger

**Comment by NDLABS-Leo** [comment]
The round is a devolved 50T for data download verification only. After review no anomalies were found and it is possible to continue and wait for the project owner to officially store it before checking it on an ongoing basis.

**Comment by NDLABS-Leo** [comment]
checker:manualTrigger

**Comment by NDLABS-Leo** [comment]
checker:manualTrigger

**Comment by NDLABS-Leo** [comment]
ready to support

**Comment by filecoin-watchdog** [comment]
checker:manualTrigger

**Comment by gimims** [comment]
checker:manualTrigger

**Comment by filecoin-watchdog** [comment]
checker:manualTrigger

**Comment by NDLABS-Leo** [comment]
checker:manualTrigger

**Comment by NDLABS-Leo** [comment]
@yuxlantian 
For the proper conduct of the project, please supplement kyb's supporting documents, which can be emailed to the <hzpd@ndlabs.io> email address via the project's suffix email address.

**Comment by NDLABS-Leo** [comment]
⚠️ 85.71% of Storage Providers have retrieval success rate equal to zero.

⚠️ The average retrieval success rate is 2.09%

Regarding the retrieval rate, ND LABS is developing a tool for retrieval rate detection, and at the moment it is possible that some sp's may not be compatible with spark's retrieval rate, so please explain the situation of the sp's you are working with.

**Comment by NDLABS-Leo** [comment]
![image](https://github.com/NDLABS-Leo/Allocator-Pathway-ND-CLOUD/assets/104019147/2f8d8ae1-43ea-4291-a3fc-1fa60df1ca34)
Mail received

**Comment by NDLABS-Leo** [comment]
checker:manualTrigger

**Comment by NDLABS-Leo** [comment]
![image](https://github.com/user-attachments/assets/af364c99-317e-41df-bf72-2fc6434c97f0)

{
    "data": [
        {
            "Id": 1,
            "ClientID": "f03064811",
            "Client": "f1ccqyhokaxxgdsdh7oayfxxzminsf6gyu6duodaa",
            "Provider": "f02826234",
            "City": "SG Singapore Singapore",
            "HttpRetrievalRate": "0.00%",
            "GraphsyncRetrievalRate": "17.58%",
            "BitswapRetrievalRate": "0.00%"
        },
        {
            "Id": 2,
            "ClientID": "f03064811",
            "Client": "f1ccqyhokaxxgdsdh7oayfxxzminsf6gyu6duodaa",
            "Provider": "f03079511",
            "City": "HK Hong Kong Hong Kong",
            "HttpRetrievalRate": "0.00%",
            "GraphsyncRetrievalRate": "10.92%",
            "BitswapRetrievalRate": "0.00%"
        },
        {
            "Id": 3,
            "ClientID": "f03064811",
            "Client": "f1ccqyhokaxxgdsdh7oayfxxzminsf6gyu6duodaa",
            "Provider": "f03066382",
            "City": "CN Sichuan Chengdu",
            "HttpRetrievalRate": "0.00%",
            "GraphsyncRetrievalRate": "13.94%",
            "BitswapRetrievalRate": "0.00%"
        },
        {
            "Id": 4,
            "ClientID": "f03064811",
            "Client": "f1ccqyhokaxxgdsdh7oayfxxzminsf6gyu6duodaa",
            "Provider": "f02980903",
            "City": "KR Seoul Seoul",
            "HttpRetrievalRate": "0.00%",
            "GraphsyncRetrievalRate": "12.52%",
            "BitswapRetrievalRate": "0.00%"
        },
        {
            "Id": 5,
            "ClientID": "f03064811",
            "Client": "f1ccqyhokaxxgdsdh7oayfxxzminsf6gyu6duodaa",
            "Provider": "f03064819",
            "City": "KR Seoul Seoul",
            "HttpRetrievalRate": "0.00%",
            "GraphsyncRetrievalRate": "10.66%",
            "BitswapRetrievalRate": "0.00%"
        },
        {
            "Id": 6,
            "ClientID": "f03064811",
            "Client": "f1ccqyhokaxxgdsdh7oayfxxzminsf6gyu6duodaa",
            "Provider": "f02956383",
            "City": "HK Hong Kong Hong Kong",
            "HttpRetrievalRate": "0.77%",
            "GraphsyncRetrievalRate": "17.20%",
            "BitswapRetrievalRate": "0.00%"
        },
        {
            "Id": 7,
            "ClientID": "f03064811",
            "Client": "f1ccqyhokaxxgdsdh7oayfxxzminsf6gyu6duodaa",
            "Provider": "f02826123",
            "City": "CN Guangdong Shenzhen",
            "HttpRetrievalRate": "0.00%",
            "GraphsyncRetrievalRate": "10.34%",
            "BitswapRetrievalRate": "0.00%"
        },
        {
            "Id": 8,
            "ClientID": "f03064811",
            "Client": "f1ccqyhokaxxgdsdh7oayfxxzminsf6gyu6duodaa",
            "Provider": "f02827151",
            "City": "CN Guangdong Shenzhen",
            "HttpRetrievalRate": "0.00%",
            "GraphsyncRetrievalRate": "14.63%",
            "BitswapRetrievalRate": "0.00%"
        },
        {
            "Id": 9,
            "ClientID": "f03064811",
            "Client": "f1ccqyhokaxxgdsdh7oayfxxzminsf6gyu6duodaa",
            "Provider": "f03046248",
            "City": "HK Hong Kong Hong Kong",
            "HttpRetrievalRate": "0.00%",
            "GraphsyncRetrievalRate": "12.03%",
            "BitswapRetrievalRate": "0.00%"
        }
    ],
    "msg": "Success",
    "status": 200
}

**Comment by NDLABS-Leo** [comment]
Query through the self-developed node retrieval rate checking tool interface, the node retrieval rate is normal

**Comment by filecoin-watchdog** [comment]
checker:manualTrigger

**Comment by NDLABS-Leo** [comment]
checker:manualTrigger

**Comment by NDLABS-Leo** [comment]
checker:manualTrigger
