### ISSUE TITLE
[DataCap Application] <AOLIGEI> - <AOLIGEICaptaiNLP>

### ISSUE THREAD

**Issue by CaptaiNLP** [NDLABS-Leo/Allocator-Pathway-ND-CLOUD#7]
### Version

1

### DataCap Applicant

CaptaiNLP

### Project ID

1

### Data Owner Name

CaptaiNLP

### Data Owner Country/Region

China

### Data Owner Industry

Information, Media & Telecommunications

### Website

www.aoligei-Fighting.com

### Social Media Handle

None

### Social Media Type

Slack

### What is your role related to the dataset

Dataset Owner

### Total amount of DataCap being requested

10

### Unit for total amount of DataCap being requested

PiB

### Expected size of single dataset (one copy)

1

### Unit for expected size of single dataset

PiB

### Number of replicas to store

10

### Weekly allocation of DataCap requested

1

### Unit for weekly allocation of DataCap requested

PiB

### On-chain address for first allocation

f17lmyguhyvvsjo5yl4purihgqndbvhw4dlagupeq

### Data Type of Application

Public, Open Commercial/Enterprise

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
Zhejiang AOLIGEI Culture Media Co., Ltd is a cultural media platform focused on the development of artists. With accurate market positioning, we’ve won a certain market share out of many competitors. Engaged in the filed of the image promotion of internet influencers, short video planning, filming training consulting, etc., not only do we have a large number of cultural media resources, but also create their own flow of IP with the professional operation teams, helping them achieve their own dreams!
Our company currently has more than 100 artists under contract, and our current business has close ties with film and television companies, social media platforms, and e-commerce.
1、Cooperating with some film and TV companies to shoot TV series and advertisement promotion works.
2、Cooperating with some social media platforms to publish videos, pictures and advertisements of our contracted artists.
3、We also do e-commerce by selling a full range of products through live-stream media.
```

### Is this project associated with other projects/ecosystem stakeholders?

Yes

### Describe the data being stored onto Filecoin

```text
The data stored on Filecoin are our business videos, commercials, image and client’s video materials.
```

### Where was the data currently stored in this dataset sourced from

My Own Storage Infra

### If you are a data preparer. What is your location (Country/Region)

None

### If you are a data preparer, how will the data be prepared? Please include tooling used and technical details?

```text
We currently store data on our own server hard drives for backup. In the future, we will mainly provide data to storage service providers through network transmission and mailing hard drives.
```

### Has this dataset been stored on the Filecoin network before? If so, please explain and make the case why you would like to store this dataset again to the network. Provide details on preparation and/or SP distribution.

```text
f099132	Guangzhou, Guangdong, CN
Hangzhou Alibaba Advertising Co.,Ltd.	4.72 TiB	10.07%	4.69 TiB	0.66%
f021704new	Shanghai, Shanghai, CN
Hangzhou Alibaba Advertising Co.,Ltd.	2.47 TiB	5.27%	2.47 TiB	0.00%
f01878534	Los Angeles, California, US
Zenlayer Inc	11.81 TiB	25.22%	11.81 TiB	0.00%
f01853104	Los Angeles, California, US
Zenlayer Inc	11.16 TiB	23.82%	11.16 TiB	0.00%
f01893023	Los Angeles, California, US
Zenlayer Inc	9.94 TiB	21.21%	9.94 TiB	0.00%
f01890456	Los Angeles, California, US
Zenlayer Inc

------
These are the storage providers we have contacted previously, and we plan to contact a few more for joint storage
```

### Please share a sample of the data

```text
Douying：
https://www.douyin.com/user/MS4wLjABAAAAqHIH7OBGnA77xHvRJNYaNXRS5MAm-2lDxNIk3dJSHtU?modal_id=7117310005006568740
https://www.douyin.com/user/MS4wLjABAAAAqHIH7OBGnA77xHvRJNYaNXRS5MAm-2lDxNIk3dJSHtU?modal_id=7116789513619361032
https://www.douyin.com/user/MS4wLjABAAAAqHIH7OBGnA77xHvRJNYaNXRS5MAm-2lDxNIk3dJSHtU?modal_id=7118665932796431647
https://www.douyin.com/user/MS4wLjABAAAAAD-lSehi3CNwG1I8bTSfQUZ-Ak2j9Rxdulx6TZNFsAc?modal_id=7026563322648579362
https://www.douyin.com/user/MS4wLjABAAAAAD-lSehi3CNwG1I8bTSfQUZ-Ak2j9Rxdulx6TZNFsAc?modal_id=7062130813122481423
https://www.douyin.com/user/MS4wLjABAAAA5Zr5L2owYCE9QuAWtxzbYfBc2Nhj0b4Pf8FBk-xyUu4?modal_id=6651515890045160711
https://www.douyin.com/user/MS4wLjABAAAA5Zr5L2owYCE9QuAWtxzbYfBc2Nhj0b4Pf8FBk-xyUu4?modal_id=7134982490384616743
https://www.douyin.com/user/MS4wLjABAAAA5Zr5L2owYCE9QuAWtxzbYfBc2Nhj0b4Pf8FBk-xyUu4?modal_id=7135387938128497958
https://www.douyin.com/user/MS4wLjABAAAA5Zr5L2owYCE9QuAWtxzbYfBc2Nhj0b4Pf8FBk-xyUu4?modal_id=7136491982939049227
https://www.douyin.com/user/MS4wLjABAAAA_UAtaMCagWq8N1RPE-KCyW9VIyt6wwhhJ3J4l7pI-tXCiK6I1TQvV1Adv9PkQj2a?modal_id=6837725081230200071
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Yearly

### For how long do you plan to keep this dataset stored on Filecoin

1.5 to 2 years

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China, North America

### How will you be distributing your data to storage providers

Cloud storage (i.e. S3), HTTP or FTP server, IPFS

### How did you find your storage providers

Slack

### Please list the provider IDs and location of the storage providers you will be working with.

```text
f02211572 | Chengdu, Sichuan | MicroAnt
f02814600 | Chengdu, Sichuan| BigMax
f02226869 | Nanchang, Jiangxi | LuckyMine
f02274508 | Hong Kong | H&W
f02329119 | Hangzhou, Zhejiang | Cryptomage
f02837293 | Seoul, Seoul | FiveByte
f01159754 | Singapore, Singapore | VITACapital
f01852363 | Singapore, Singapore | HectorLi
f02321504 | Los Angeles, California | ipollo
f02320312 | Los Angeles, California | R1
f02327534 | Los Angeles, California | ipollo
f02322031 | Los Angeles, California | ipollo
f02320270 | Los Angeles, California | R1
f01853077 | Singapore, Singapore | Alpha100
```

### How do you plan to make deals to your storage providers

Boost client, Lotus client

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by NDLABS-Leo** [comment]
Thank you for re-applying because of the bug. Link: https://github.com/NDLABS-Leo/Allocator-Pathway-ND-CLOUD/issues/3
